### ISSUE TITLE
UI Dosent LOAD

### ISSUE THREAD

**Issue by Dontmindmes** [RoudyES/ShareScreen#1]
https://i.imgur.com/x9HjmfG.png

when i launch screenshare the program does not do anything it just keeps at a white screen

**Comment by RoudyES** [comment]
@Dontmindmes Did you run the broadcaster service as admin ?
The problem is that SignalR client is not connecting to the hub which keeps the UI waiting, launching the broadcaster as admin should initiate the connection just fine.

**Comment by Dontmindmes** [comment]
Hi yes i did i ran both as admin too, and it is still a white screen, i ran broadcaster first, i also put the internal IP and my external IP an nothing happened, i am port forwarded too but nothing changed

**Comment by Dontmindmes** [comment]
I was able to get it to work! Thank you!

I have a question I can use this for external devices right? devices running on diffrent networks? like my friends computer? all i have to do is have him run broadcaster.exe and ill be able to connect? is this possible?

**Comment by RoudyES** [comment]
@Dontmindmes Cool! if it wasn't an admin issue what was the problem ?
Unfortunately no, the broadcaster must be visible for both clients. It either has to run somewhere in the local network, or (like anydesk and teamviewer) run it in a public server where anyone can reach it.

**Comment by Dontmindmes** [comment]
do you have any similar projects that can do the same thing but on devices out side the network?

**Comment by RoudyES** [comment]
The limitations isn't due to the project i'm afraid. The problem is, both clients must be able to reach the same broadcaster, this way, the broadcaster will know where the image is coming from and to who it should send it. Unless you have a public ip or somehwere reachable by both networks, you won't be able to use it ouside a local network.
This solution basically works best in an intranet where the users prefer not to use an online service. Also, the project is written and separated in a way which makes it extremely easy for other developers to incorporate it into their own projects.
